'use strict';
let csrf='',busy=false,nextAction='status',lastAdvanced='',lastLatest='',lastPreview='';
let cameraKey='',cameraRoles=[],previewRoles=[],snapshot=null,submitting=false,refreshing=false,connected=false;
const timeText=value=>new Date(value).toLocaleTimeString('en-CA',{timeZone:'America/Toronto',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'short'});
function showDetails(title,text){$('#log-dialog h2').textContent=title;$('#log-text').textContent=text;$('#log-dialog').showModal();}
function disableControls(){for(const id of ['main-action','framing','refresh','safe-stop','collect'])$('#'+id).disabled=true;}
function elapsed(){const r=snapshot?.remote||{},confirmed=Object.values(r.states||{}).includes('recording');const start=snapshot?.jobs?.find(j=>j.action==='start'&&j.state==='done'&&j.phase==='recording');const valid=confirmed&&start&&r.pending_take===start.take_id;const seconds=valid?Math.max(0,Math.floor((Date.now()-Date.parse(start.updated))/1000)):0;$('#elapsed').textContent=valid?[Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(x=>String(x).padStart(2,'0')).join(':'):'—:—';$('#timer-note').textContent=valid?(connected?'Since Start confirmation':'Last confirmed · connection lost'):confirmed?'Start time unavailable':'No confirmed recording';}
const $=s=>document.querySelector(s);
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function error(message){$('#error').textContent=message;$('#error').hidden=!message;}
async function api(path,body){const options={credentials:'same-origin',cache:'no-store'};if(body!==undefined){options.method='POST';options.headers={'Content-Type':'application/json','X-Phone-CSRF':csrf};options.body=JSON.stringify(body);}options.signal=AbortSignal.timeout(10000);const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw new Error(data.error||r.statusText);return data;}
function hideFrames(){for(const role of previewRoles){$('#'+role+'-image').hidden=true;$('#'+role+'-image').removeAttribute('src');}lastPreview='';}
async function action(name,take){if(submitting||busy||!connected)return;submitting=true;disableControls();try{error('');if(name==='start'||name==='preview')hideFrames();await api('/api/jobs',{action:name,...(take?{take_id:take}:{}),request_id:crypto.randomUUID().replaceAll('-','')});}catch(e){error(e.message+' — inspect Activity before repeating a command.');}finally{submitting=false;await refresh();}}

async function deleteTake(take){
 if(submitting||busy||!connected)return;
 const r=snapshot?.remote||{};
 if(Object.values(r.states||{}).includes('recording')||(r.pending_take&&(!r.pending_review||r.pending_take!==take)))return error('Finish stopping and inventory checks first.');
 const scope=r.pending_take===take?'phones':snapshot.takes.some(t=>t.id===take)?'both':'remote';
 const required='DELETE '+take+' '+scope.toUpperCase();
 const detail=scope==='phones'?'Deletes the exact stopped recording from ALL phones. NO saved Mac copy exists.':scope==='remote'?'Deletes the capture folder on this Mac. No verified editing copy exists.':'Removes BOTH local copies (capture and editing), including footage and generated edit files. These are on one Mac, not separate backups. If imported, removes its dedicated Resolve project only when it contains this take alone.';
 const answer=window.prompt('Permanently delete take '+take+'?\n\n'+detail+' Other takes/projects are protected.\n\nNO backups. NO Trash. Cannot undo.\nType '+required+' to confirm:');
 if(answer!==required){if(answer!==null)error('Confirmation did not match. Nothing deleted.');return;}
 submitting=true;disableControls();
 try{await api('/api/delete-take',{take_id:take,confirmation:answer,request_id:crypto.randomUUID().replaceAll('-','')});error('');}
 catch(e){error(e.message+' — inspect Activity before retrying deletion.');}
 finally{submitting=false;await refresh();}
}
function button(label,fn,disabled=false){const b=node('button',label,'secondary');b.disabled=disabled;b.addEventListener('click',fn);return b;}
function takeActions(t,compact=false){const buttons=node('div',undefined,'buttons');if(t.local){buttons.append(button('Show files',()=>api('/api/reveal',{take_id:t.id}).catch(e=>error(e.message))));if(t.local.import_status?.ok)buttons.append(button('Open Resolve',()=>api('/api/open-resolve',{take_id:t.id}).catch(e=>error(e.message)),busy));if(t.local.sync_ok)buttons.append(button(t.local.import_status?.ok?'Import receipt':'Import to Resolve',()=>t.local.import_status?.ok?showDetails('Resolve import receipt','This take was imported previously. This does not reopen or verify the current project, and does not overwrite your edits.\n\n'+JSON.stringify(t.local.import_status,null,2)):action('import',t.id),busy));}if(!compact||!t.local?.sync_ok)buttons.append(button(t.pending?'Transfer recording':t.local?'Prepare again':'Verify copy & prepare',()=>t.pending?action('collect'):action('prepare',t.id),busy));if(t.local||t.remote||t.pending){const r=snapshot?.remote||{};const del=button('Delete take…',()=>deleteTake(t.id),busy||submitting||!connected||Boolean(r.pending_take&&(!r.pending_review||r.pending_take!==t.id))||Object.values(r.states||{}).includes('recording'));del.classList.add('delete-take');buttons.append(del);}return buttons;}
function cameraDetails(c){
 const r=snapshot?.remote||{},p=r.readiness?.phones?.[c.role]||{},m=p.metrics||{},t=r.transports?.[c.role];
 const blockers=p.blockers||[],warnings=p.warnings||[];
 const advice=blockers.length?'Resolve the blockers below, then Check cameras again.':r.states?.[c.role]==='recording'?'Recording was last confirmed. Health readings are not polled during capture.':!r.observed?'Keep the camera app open and run Check cameras.':'Refresh stale readings before Start. Missing temperature requires a manual heat check.';
 return [c.model+' · configured '+c.video_label,'State: '+(r.states?.[c.role]||'Unknown'),'Last observation: '+(r.observed?timeText(r.observed):'Not checked'),'Connection: '+(t?t.mode+' · '+t.endpoint:'Not verified'),'','Battery: '+(m.battery_percent!=null?m.battery_percent+'%':'Unavailable'),'Storage: '+(m.free_bytes!=null?(m.free_bytes/1024**3).toFixed(1)+' GiB free':'Unavailable'),'Power: '+(m.external_power===true?'Connected':m.external_power===false?'Battery':'Unavailable'),'Battery temperature: '+(m.battery_temperature_c!=null?m.battery_temperature_c+'°C':'Unavailable — manually check for excessive heat'),'','NEXT STEP',advice,'','START BLOCKERS',...(blockers.length?blockers.map(x=>'• '+x):['No blockers reported; this does not replace fresh readiness checks.']),'','WARNINGS',...(warnings.length?warnings.map(x=>'• '+x):['None reported.'])].join('\n');
}
function setupCameras(data){
const definitions=data.cameras||[];const key=JSON.stringify([data.config_id,definitions]);if(key===cameraKey)return;cameraKey=key;
cameraRoles=definitions.filter(c=>c.enabled).map(c=>c.role);previewRoles=definitions.filter(c=>c.enabled&&c.preview).map(c=>c.role);lastPreview='';
$('#camera-count').textContent=String(cameraRoles.length);$('#camera-cards').replaceChildren();for(const c of definitions.filter(c=>c.enabled)){
const card=node('article',undefined,'camera'),row=node('div',undefined,'row'),status=node('span','Needs checking','status');status.id=c.role+'-status';row.append(node('strong',c.name),status);
const sub=node('small',c.model+' · Configured '+c.video_label+' · '),transport=node('span','connection unchecked');transport.id=c.role+'-transport';sub.append(transport);card.append(row,sub);
const health=node('p','Check health before Start','fine'),warnings=node('p','','fine camera-warning');health.id=c.role+'-health';warnings.id=c.role+'-warnings';card.append(health,warnings);const metrics=node('p','','camera-metrics');metrics.id=c.role+'-metrics';card.append(metrics);const info=button('Details',()=>showDetails(c.name+' · cached camera details',cameraDetails(c)));info.className='camera-info secondary';card.append(info);
if(c.preview){const image=node('img');image.id=c.role+'-image';image.alt=c.name+' phone screen snapshot';image.hidden=true;image.addEventListener('error',()=>{image.hidden=true;error(c.name+' snapshot could not load. Use Check framing again only while idle.');});card.append(image,node('div','No preview','frame-placeholder'));}else card.append(node('p','Check framing on the phone screen. No preview stream.','fine'));
$('#camera-cards').append(card);}
$('#camera-plan').textContent='Planned, not enabled: '+(definitions.filter(c=>!c.enabled).map(c=>c.name).join(', ')||'none')+'. Configuration changes require deliberate Wi-Fi onboarding on this Mac.';
}
function render(data){snapshot=data;connected=true;setupCameras(data);busy=Boolean(data.active)||submitting;const r=data.remote,states=r.states||{},age=r.observed?(Date.now()-Date.parse(r.observed))/1000:Infinity;const idle=cameraRoles.length>0&&Object.keys(states).length===cameraRoles.length&&cameraRoles.every(role=>states[role]==='idle');const health=r.readiness;const healthAge=health?.checked_at?(Date.now()-Date.parse(health.checked_at))/1000:Infinity;const healthFresh=healthAge>=-5&&healthAge<=120&&health?.config_id===data.config_id&&r.config_id===data.config_id;const healthOK=healthFresh&&health?.ok===true&&data.local_storage?.ok===true;const recording=Object.values(states).includes('recording');const active=data.jobs.find(j=>j.id===data.active);let phase=active?.phase||'';
$('#connection').textContent='Dashboard connected';$('#checked-at').textContent=r.observed?'Last camera observation '+timeText(r.observed)+' · '+(age>120?'stale':Math.max(0,Math.floor(age))+'s ago'):'Camera state not checked';$('#storage-note').textContent=data.local_storage?.free_bytes!=null?'This Mac · '+(data.local_storage.free_bytes/1024**3).toFixed(1)+' GiB free':'Local storage unavailable';$('#source').textContent='Project: '+data.source_root;
for(const role of cameraRoles){const transport=r.transports?.[role];const badge=$('#'+role+'-transport');badge.textContent=transport?(transport.mode==='wifi'?'Wi-Fi':'USB'):'connection unchecked';badge.title=transport?transport.endpoint+' · '+transport.security:'';const status=states[role];const detail=health?.phones?.[role];const label=status==='recording'?'Last confirmed recording':status==='idle'&&age<=120?(healthFresh?(detail?.ok?'Ready':'Blocked'):'Check health'):'Needs checking';const metrics=detail?.metrics||{};const summary=[];if(metrics.battery_percent!=null)summary.push(Math.round(metrics.battery_percent)+'% battery');else summary.push('Battery unavailable');if(metrics.free_bytes!=null)summary.push((metrics.free_bytes/1024**3).toFixed(1)+' GiB free');else summary.push('Storage unavailable');if(metrics.battery_temperature_c!=null)summary.push('Battery '+metrics.battery_temperature_c.toFixed(1)+'°C');if(metrics.external_power===true)summary.push('Powered');else if(metrics.charging===false)summary.push('Not charging');if(metrics.battery_temperature_c==null)summary.push('Temperature unavailable');$('#'+role+'-health').textContent=(healthFresh?'':'Previous/unverified readings · ')+(summary.join(' · ')||'Health unavailable');const compact=[];compact.push(metrics.battery_percent!=null?Math.round(metrics.battery_percent)+'% battery':'Battery —');compact.push(metrics.free_bytes!=null?(metrics.free_bytes/1024**3).toFixed(1)+' GiB free':'Storage —');compact.push(metrics.battery_temperature_c!=null?metrics.battery_temperature_c.toFixed(0)+'°C':'Temp —');$('#'+role+'-metrics').textContent=compact.join(' · ');$('#'+role+'-metrics').title=$('#'+role+'-health').textContent;$('#'+role+'-warnings').textContent=[...(detail?.blockers||[]),...(detail?.warnings||[])].join(' · ');$('#'+role+'-status').textContent=label;$('#'+role+'-status').className='status '+(label==='Ready'?'idle':label==='Last confirmed recording'?'recording':'');}
let label,note,step=-1;
if(active){label=active.state==='uncertain'?'Needs attention':active.action==='preview'?'Checking framing…':active.action==='status'?'Checking cameras…':active.action==='start'?'Starting…':phase==='copy_verify_and_audio_sync'?'Copying & syncing…':phase==='verifying_local_copy'?'Copying & verifying…':phase==='audio_sync'?'Aligning audio…':phase==='resolve_import'?'Importing to Resolve…':active.action==='prepare'?'Preparing take…':active.action==='import'?'Opening in Resolve…':active.action==='delete'?'Deleting take…':active.action==='stop_review'?'Stopping & checking files…':'Collecting recording…';note=active.state==='uncertain'?'Open Activity & recovery to reconcile this job. No recording command will be retried automatically.':'Processing continues if you close this window.';if(active.action==='start')step=0;if(['stop','collect'].includes(active.action))step=1;if(active.action==='prepare'||['copy_verify_and_audio_sync','verifying_local_copy'].includes(phase))step=2;if(phase==='audio_sync')step=3;if(phase==='resolve_import'||active.action==='import')step=4;}
else if(recording){label='Stop & review';nextAction='stop_review';note='Recording was confirmed on '+Object.values(states).filter(x=>x==='recording').length+'/'+cameraRoles.length+' cameras. No continuous phone polling; Stop rechecks states.';step=0;}
else if(r.pending_take){label=r.pending_review?'Transfer recording':'Finish collection';nextAction='collect';note=r.pending_review?'Stopped on phones. Transfer or delete below; no Mac copy yet.':'A take is waiting for safe collection. Unknown camera states will block transfer.';step=1;}
else if(idle&&age>=-5&&age<=120&&healthOK){label='Start recording';nextAction='start';note='Cameras ready. One clip per camera; segmented takes need manual review.';}
else{label='Check cameras';nextAction='status';note='Open the camera apps, then check readiness.';}
if(!busy&&!recording&&!r.pending_take&&idle&&!healthOK){note=!data.local_storage?.ok?'This Mac needs at least 5 GiB free.':healthFresh?'Readiness needs attention; review the camera warnings, then check again.':'Refresh camera health before Start.';}
const attention=active?.state==='uncertain'||(!busy&&data.jobs[0]&&['needs_review','uncertain'].includes(data.jobs[0].state));const session=attention?'Needs attention':active?label.replace('…',''):recording?'Recording confirmed':r.pending_take?'Collection pending':nextAction==='start'?'Ready to record':data.takes[0]?.import_status?.ok?'Ready to edit':'Check cameras';$('#session-state').textContent=session;document.body.dataset.session=attention?'attention':recording?'recording':'idle';$('#state-kicker').textContent=active?'JOB IN PROGRESS':'SESSION';elapsed();$('#main-action').textContent=label;$('#main-action').disabled=busy||submitting;$('#main-action').className=recording?'stop':'primary';$('#status-note').textContent=attention?(data.jobs[0]?.error||'The last job needs review.')+' Open Activity & recovery. '+(recording?'Recording was last confirmed; Stop remains available.':''):note;
$('#framing').disabled=busy||recording||Boolean(r.pending_take)||!idle||age>120||age< -5||r.config_id!==data.config_id;$('#framing').textContent=data.preview?'Refresh framing':'Check framing';$('#refresh').disabled=busy||recording||Boolean(r.pending_take);$('#safe-stop').disabled=busy;$('#collect').disabled=busy||!r.pending_take;
if(data.preview&&!busy&&!recording){if(lastPreview!==data.preview.observed){for(const role of previewRoles){const img=$('#'+role+'-image');img.src='/api/preview?camera='+role+'&v='+encodeURIComponent(data.preview.observed);img.hidden=false;}lastPreview=data.preview.observed;}$('#preview-note').textContent='Still snapshots · '+timeText(data.preview.observed)+' · expire in '+data.preview.expires_in+'s. Click Refresh framing to update.';}else{hideFrames();$('#preview-note').textContent=active?.action==='preview'?'Checking every enabled camera is idle before taking snapshots…':'Temporary stills · idle only';}
const merged=new Map();for(const t of r.takes||[])merged.set(t.id,{id:t.id,remote:t});if(r.pending_take&&r.pending_review)merged.set(r.pending_take,{id:r.pending_take,pending:true});for(const t of data.takes)merged.set(t.id,{...(merged.get(t.id)||{}),id:t.id,local:t});const takes=[...merged.values()].sort((a,b)=>b.id.localeCompare(a.id));const latest=takes[0];const lastWork=data.jobs.find(j=>['start','stop','collect','prepare'].includes(j.action));if(step<0&&!active&&lastWork?.phase==='timeline_ready'&&(Date.now()-Date.parse(lastWork.updated))<60000)step=4;$('#progress').hidden=false;
$('#progress').querySelectorAll('li').forEach((e,i)=>{e.className=i===step?'current':i<step?'complete':'';if(i===step)e.setAttribute('aria-current','step');else e.removeAttribute('aria-current');});
const latestKey=JSON.stringify([latest,busy,r.pending_take,r.pending_review,states]);if(latestKey!==lastLatest){lastLatest=latestKey;$('#latest').replaceChildren();$('#latest-status').textContent=latest?.local?.import_status?.ok?'Resolve import saved':latest?.local?.sync_ok?'Sync approved · import needed':latest?.pending?'Stopped · awaiting transfer':latest?.remote&&!latest?.local?'Collected · awaiting verified copy':latest?'Awaiting preparation':'No take yet';if(latest){$('#latest').append(node('p',latest.id,'take-title'),takeActions(latest,true));if(latest.local?.sync_ok){const imported=latest.local.import_status?.ok;$('#latest').append(node('p',imported?'Saved full camera tracks · visual sync review needed.':'Audio sync passed. Resolve import still needs attention.','fine'));}else if(latest.local?.sync_error)$('#latest').append(node('p',latest.local.sync_error,'fine'));}else $('#latest').append(node('p','Your next take will appear here.','muted'));}
const signature=JSON.stringify([r.takes,r.pending_take,r.pending_review,states,data.jobs,data.takes,busy]);if(signature===lastAdvanced)return;lastAdvanced=signature;
$('#jobs').replaceChildren();for(const j of data.jobs.slice(0,10)){const div=node('div',undefined,'job'),row=node('div',undefined,'row');row.append(node('span',j.action.toUpperCase()+' · '+(j.phase||j.state).replaceAll('_',' '),'name'),node('span',j.state.replaceAll('_',' '),'pill '+j.state));div.append(row,node('div',new Date(j.created).toLocaleString('en-CA',{timeZone:'America/Toronto',timeZoneName:'short'})+(j.take_id?' · '+j.take_id:''),'fine'));if(j.error)div.append(node('p',j.error,'fine'));const b=node('div',undefined,'buttons');b.append(button('View log',async()=>{try{showDetails('Job log',(await api('/api/log?id='+j.id)).text);}catch(e){error(e.message);}}));if(j.state==='uncertain')b.append(button('Reconcile — no retry',async()=>{try{await api('/api/recover',{id:j.id});await refresh();}catch(e){error(e.message);}}));div.append(b);if(j.result){const details=node('details');details.append(node('summary','Job results'),node('pre',JSON.stringify(j.result,null,2)));div.append(details);}$('#jobs').append(div);}
$('#takes').replaceChildren();for(const t of takes){const div=node('div',undefined,'take');div.append(node('strong',t.id));if(t.remote)div.append(node('div','Capture on this Mac: '+(t.remote.path||'Collected take; awaiting verified local copy'),'path'));if(t.local)div.append(node('div','This Mac: '+t.local.path,'path'),node('p','Cameras: '+(t.local.cameras||[]).join(', ')+' · '+(t.local.import_status?.ok?'Resolve import saved':t.local.sync_ok?'Audio aligned; import pending':'Preparation needed'),'fine'));div.append(takeActions(t));$('#takes').append(div);}
if(!takes.length)$('#takes').append(node('p','No takes in the current verified library.','empty'));if(!data.jobs.length)$('#jobs').append(node('p','No recent jobs.','empty'));
}
async function refresh(){if(refreshing)return;refreshing=true;try{render(await api('/api/state'));if($('#error').textContent==='Failed to fetch')error('');}catch(e){connected=false;$('#connection').textContent='Disconnected';$('#session-state').textContent='Connection lost';$('#status-note').textContent='Jobs and recording may still be running. Reconnect; do not repeat commands blindly.';disableControls();hideFrames();elapsed();error(e.message);}finally{refreshing=false;}}

async function init(){try{const token=new URLSearchParams(location.hash.slice(1)).get('token');if(token){history.replaceState(null,'',location.pathname);csrf=(await api('/api/auth',{token})).csrf;}else csrf=(await api('/api/session')).csrf;$('#auth').hidden=true;await refresh();setInterval(refresh,2500);}catch(e){$('#auth').hidden=false;error(e.message);}}
$('#open-library').addEventListener('click',()=>$('#library-dialog').showModal());$('#open-advanced').addEventListener('click',()=>$('#advanced').showModal());for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>$('#'+b.dataset.close).close());
$('#export-diagnostics').addEventListener('click',()=>{if(!snapshot)return;const safe={version:1,exported:new Date().toISOString(),connected,active:Boolean(snapshot.active),cameras:snapshot.cameras.map(c=>({role:c.role,name:c.name,enabled:c.enabled})),states:snapshot.remote.states||{},observed:snapshot.remote.observed||null,local_storage_ok:snapshot.local_storage?.ok??null,phones:Object.fromEntries(Object.entries(snapshot.remote.readiness?.phones||{}).map(([role,p])=>[role,{ok:p.ok,battery_percent:p.metrics?.battery_percent,free_bytes:p.metrics?.free_bytes,battery_temperature_c:p.metrics?.battery_temperature_c,blockers:(p.blockers||[]).length,warnings:(p.warnings||[]).length}])),jobs:snapshot.jobs.map(j=>({action:j.action,state:j.state,phase:j.phase,created:j.created,updated:j.updated})),take_count:snapshot.takes.length};const url=URL.createObjectURL(new Blob([JSON.stringify(safe,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='phone-recording-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});setInterval(elapsed,1000);
$('#main-action').addEventListener('click',()=>action(nextAction));$('#framing').addEventListener('click',()=>action('preview'));$('#refresh').addEventListener('click',()=>action('status'));$('#safe-stop').addEventListener('click',()=>action('stop_review'));$('#collect').addEventListener('click',()=>action('collect'));$('#close-log').addEventListener('click',()=>$('#log-dialog').close());init();
